# Generated by Django 3.2.8 on 2021-10-18 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Вид очереди',
                'verbose_name_plural': 'Виды очередей',
            },
        ),
        migrations.AlterModelOptions(
            name='profilecategory',
            options={'verbose_name': 'Категория профилей', 'verbose_name_plural': 'Категории профилей'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='saturday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='sunday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='friday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='monday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='thursday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tuesday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='wednesday',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.scheduletype'),
            preserve_default=False,
        ),
    ]
