# Generated by Django 3.2.8 on 2021-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211018_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
