# Generated by Django 3.2.8 on 2021-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_screen_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
