# Generated by Django 3.2.8 on 2023-09-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_screen_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('screens', models.ManyToManyField(blank=True, to='main.Screen')),
            ],
            options={
                'verbose_name': 'Слайд экранов',
                'verbose_name_plural': 'Слайды экранов',
            },
        ),
    ]
