# Generated by Django 3.2.8 on 2023-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slider_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='time_for_slide',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
